version: '3.8'

services:
  game-app:
    build:
      context: ./php
    container_name: game-app
    volumes:
      - ./src:/var/www/html
    depends_on:
      - game-mysql

  game-mysql:
    image: mysql:5.7
    container_name: game-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: game
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"

  nginx:
    image: nginx:stable-alpine
    container_name: game-nginx
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - game-app
